[package]
name = "example-protobuf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Protobuf Page generated in-crate and serialized as Markdown"

[dependencies]
buffa = { workspace = true }
buffa-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_markdown = { workspace = true }

[lints]
workspace = true
