load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

exports_files(["Cargo.toml"])

rust_library(
    name = "serde_markdown",
    srcs = glob(["src/**/*.rs"]),
    compile_data = glob(
        ["testdata/markdown/**/*.md"],
        allow_empty = True,
    ),
    crate_name = "serde_markdown",
    visibility = ["//visibility:public"],
    deps = [
        "@cargo//:pulldown-cmark",
        "@cargo//:serde",
        "@cargo//:serde_json",
        "@cargo//:toml",
        "@cargo//:yaml_serde",
    ],
)

rust_test(
    name = "serde_markdown_test",
    compile_data = glob(
        ["testdata/markdown/**/*.md"],
        allow_empty = True,
    ),
    crate = ":serde_markdown",
    visibility = ["//rust:__pkg__"],
    deps = [
        "//rust/generated",
        "@cargo//:buffa",
        "@cargo//:buffa-types",
        "@cargo//:serde_json",
    ],
)
