load("@bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@bazel_utils_buf//:buf.bzl", "buf_format", "buf_generate", "buf_lint_test", "buf_module", "buf_plugin")
load("//bazel:compat.bzl", "NOT_WINDOWS")

exports_files(
    ["options.proto"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "protos",
    srcs = glob(["**/*.proto"]),
    visibility = ["//visibility:public"],
)

buf_module(
    name = "module",
    srcs = [
        ":protos",
        "//rust/examples/protobuf:protos",
    ],
    config = "//:buf.yaml",
    visibility = ["//visibility:public"],
)

buf_lint_test(
    name = "lint",
    size = "small",
    module = ":module",
    target_compatible_with = NOT_WINDOWS,
)

buf_format(
    name = "format",
    module = ":module",
)

buf_plugin(
    name = "protoc-gen-buffa-packaging",
    actual = "@cargo//:protoc-gen-buffa-packaging__protoc-gen-buffa-packaging",
    visibility = ["//visibility:public"],
)

buf_generate(
    name = "rust",
    module = ":module",
    plugins = [
        ":protoc-gen-buffa-packaging",
    ],
    template = "//:buf.gen.rust.yaml",
)

write_source_files(
    name = "generate",
    check_that_out_file_exists = False,
    files = {
        "//rust/generated:markdown": ":rust",
    },
)
