// @generated by buffa-codegen. DO NOT EDIT.
// source: markdown/options.proto

///Extension `body` on `.google.protobuf.FieldOptions` (field 20260917).
pub const BODY: ::buffa::Extension<::buffa::extension::codecs::Bool> = ::buffa::Extension::new(
    20260917u32,
    "google.protobuf.FieldOptions",
);
#[doc(hidden)]
pub const __BODY_JSON_EXT: ::buffa::type_registry::JsonExtEntry = ::buffa::type_registry::JsonExtEntry {
    number: 20260917u32,
    full_name: "markdown.body",
    extendee: "google.protobuf.FieldOptions",
    to_json: ::buffa::extension_registry::helpers::bool_to_json,
    from_json: {
        fn __from_json(
            value: ::buffa::serde_json::Value,
            number: u32,
        ) -> ::core::result::Result<
            ::buffa::alloc::vec::Vec<::buffa::UnknownField>,
            ::buffa::alloc::string::String,
        > {
            if value.is_null() {
                return ::core::result::Result::Ok(::buffa::alloc::vec::Vec::new());
            }
            ::buffa::extension_registry::helpers::bool_from_json(value, number)
        }
        __from_json
    },
};
