// @generated by buffa-codegen. DO NOT EDIT.
// source: markdown/testdata/proto3.proto

#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct Proto3Page {
    /// Field 1: `title`
    #[serde(
        rename = "title",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub title: ::buffa::alloc::string::String,
    /// Field 2: `body`
    #[serde(rename = "body", skip_serializing_if = "::core::option::Option::is_none")]
    pub body: ::core::option::Option<::buffa::alloc::string::String>,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for Proto3Page {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Proto3Page")
            .field("title", &self.title)
            .field("body", &self.body)
            .finish()
    }
}
impl Proto3Page {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/markdown.testdata.Proto3Page";
}
impl Proto3Page {
    #[must_use = "with_* setters return `self` by value; assign or chain the result"]
    #[inline]
    ///Sets [`Self::body`] to `Some(value)`, consuming and returning `self`.
    pub fn with_body(
        mut self,
        value: impl Into<::buffa::alloc::string::String>,
    ) -> Self {
        self.body = Some(value.into());
        self
    }
}
::buffa::impl_default_instance!(Proto3Page);
impl ::buffa::MessageName for Proto3Page {
    const PACKAGE: &'static str = "markdown.testdata";
    const NAME: &'static str = "Proto3Page";
    const FULL_NAME: &'static str = "markdown.testdata.Proto3Page";
    const TYPE_URL: &'static str = "type.googleapis.com/markdown.testdata.Proto3Page";
}
impl ::buffa::Message for Proto3Page {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.title.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.title) as u64;
        }
        if let Some(ref v) = self.body {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.title.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.title, buf);
        }
        if let Some(ref v) = self.body {
            ::buffa::types::put_string_field(2u32, v, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.title, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(
                    self.body.get_or_insert_with(::buffa::alloc::string::String::new),
                    buf,
                )?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.title.clear();
        self.body = ::core::option::Option::None;
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for Proto3Page {
    const PROTO_FQN: &'static str = "markdown.testdata.Proto3Page";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for Proto3Page {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __PROTO3PAGE_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/markdown.testdata.Proto3Page",
    to_json: ::buffa::type_registry::any_to_json::<Proto3Page>,
    from_json: ::buffa::type_registry::any_from_json::<Proto3Page>,
    is_wkt: false,
};
