// @generated by buffa-codegen. DO NOT EDIT.
// source: markdown/testdata/page.proto

#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct Page {
    /// Field 1: `field1`
    #[serde(rename = "field1", skip_serializing_if = "::core::option::Option::is_none")]
    pub field1: ::core::option::Option<::buffa::alloc::string::String>,
    /// Field 2: `field2`
    #[serde(rename = "field2", skip_serializing_if = "::core::option::Option::is_none")]
    pub field2: ::core::option::Option<::buffa::alloc::string::String>,
    /// Field 3: `field3`
    #[serde(
        rename = "field3",
        with = "::buffa::json_helpers::opt_int32",
        skip_serializing_if = "::core::option::Option::is_none"
    )]
    pub field3: ::core::option::Option<i32>,
    /// Field 4: `text1`
    #[serde(rename = "text1", skip_serializing_if = "::core::option::Option::is_none")]
    pub text1: ::core::option::Option<::buffa::alloc::string::String>,
    /// Field 5: `published`
    #[serde(
        rename = "published",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub published: ::buffa::MessageField<
        ::buffa_types::google::protobuf::Timestamp,
        ::buffa::Inline<::buffa_types::google::protobuf::Timestamp>,
    >,
    /// Field 6: `appendix`
    #[serde(
        rename = "appendix",
        skip_serializing_if = "::core::option::Option::is_none"
    )]
    pub appendix: ::core::option::Option<::buffa::alloc::string::String>,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for Page {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Page")
            .field("field1", &self.field1)
            .field("field2", &self.field2)
            .field("field3", &self.field3)
            .field("text1", &self.text1)
            .field("published", &self.published)
            .field("appendix", &self.appendix)
            .finish()
    }
}
impl Page {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/markdown.testdata.Page";
}
impl Page {
    #[must_use = "with_* setters return `self` by value; assign or chain the result"]
    #[inline]
    ///Sets [`Self::field1`] to `Some(value)`, consuming and returning `self`.
    pub fn with_field1(
        mut self,
        value: impl Into<::buffa::alloc::string::String>,
    ) -> Self {
        self.field1 = Some(value.into());
        self
    }
    #[must_use = "with_* setters return `self` by value; assign or chain the result"]
    #[inline]
    ///Sets [`Self::field2`] to `Some(value)`, consuming and returning `self`.
    pub fn with_field2(
        mut self,
        value: impl Into<::buffa::alloc::string::String>,
    ) -> Self {
        self.field2 = Some(value.into());
        self
    }
    #[must_use = "with_* setters return `self` by value; assign or chain the result"]
    #[inline]
    ///Sets [`Self::field3`] to `Some(value)`, consuming and returning `self`.
    pub fn with_field3(mut self, value: i32) -> Self {
        self.field3 = Some(value);
        self
    }
    #[must_use = "with_* setters return `self` by value; assign or chain the result"]
    #[inline]
    ///Sets [`Self::text1`] to `Some(value)`, consuming and returning `self`.
    pub fn with_text1(
        mut self,
        value: impl Into<::buffa::alloc::string::String>,
    ) -> Self {
        self.text1 = Some(value.into());
        self
    }
    #[must_use = "with_* setters return `self` by value; assign or chain the result"]
    #[inline]
    ///Sets [`Self::appendix`] to `Some(value)`, consuming and returning `self`.
    pub fn with_appendix(
        mut self,
        value: impl Into<::buffa::alloc::string::String>,
    ) -> Self {
        self.appendix = Some(value.into());
        self
    }
}
::buffa::impl_default_instance!(Page);
impl ::buffa::MessageName for Page {
    const PACKAGE: &'static str = "markdown.testdata";
    const NAME: &'static str = "Page";
    const FULL_NAME: &'static str = "markdown.testdata.Page";
    const TYPE_URL: &'static str = "type.googleapis.com/markdown.testdata.Page";
}
impl ::buffa::Message for Page {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if let Some(ref v) = self.field1 {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if let Some(ref v) = self.field2 {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if let Some(v) = self.field3 {
            size += 1u64 + ::buffa::types::int32_encoded_len(v) as u64;
        }
        if let Some(ref v) = self.text1 {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if self.published.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.published.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if let Some(ref v) = self.appendix {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if let Some(ref v) = self.field1 {
            ::buffa::types::put_string_field(1u32, v, buf);
        }
        if let Some(ref v) = self.field2 {
            ::buffa::types::put_string_field(2u32, v, buf);
        }
        if let Some(v) = self.field3 {
            ::buffa::types::put_int32_field(3u32, v, buf);
        }
        if let Some(ref v) = self.text1 {
            ::buffa::types::put_string_field(4u32, v, buf);
        }
        if self.published.is_set() {
            ::buffa::types::put_len_delimited_header(
                5u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.published.write_to(__cache, buf);
        }
        if let Some(ref v) = self.appendix {
            ::buffa::types::put_string_field(6u32, v, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(
                    self.field1.get_or_insert_with(::buffa::alloc::string::String::new),
                    buf,
                )?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(
                    self.field2.get_or_insert_with(::buffa::alloc::string::String::new),
                    buf,
                )?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.field3 = ::core::option::Option::Some(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(
                    self.text1.get_or_insert_with(::buffa::alloc::string::String::new),
                    buf,
                )?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.published.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(
                    self
                        .appendix
                        .get_or_insert_with(::buffa::alloc::string::String::new),
                    buf,
                )?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.field1 = ::core::option::Option::None;
        self.field2 = ::core::option::Option::None;
        self.field3 = ::core::option::Option::None;
        self.text1 = ::core::option::Option::None;
        self.published = ::buffa::MessageField::none();
        self.appendix = ::core::option::Option::None;
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for Page {
    const PROTO_FQN: &'static str = "markdown.testdata.Page";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for Page {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __PAGE_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/markdown.testdata.Page",
    to_json: ::buffa::type_registry::any_to_json::<Page>,
    from_json: ::buffa::type_registry::any_from_json::<Page>,
    is_wkt: false,
};
