// @generated by buffa-codegen. DO NOT EDIT.
// source: markdown/testdata/page.proto

#[derive(Clone, Debug, Default)]
pub struct PageView<'a> {
    /// Field 1: `field1`
    pub field1: ::core::option::Option<&'a str>,
    /// Field 2: `field2`
    pub field2: ::core::option::Option<&'a str>,
    /// Field 3: `field3`
    pub field3: ::core::option::Option<i32>,
    /// Field 4: `text1`
    pub text1: ::core::option::Option<&'a str>,
    /// Field 5: `published`
    pub published: ::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'a>,
    >,
    /// Field 6: `appendix`
    pub appendix: ::core::option::Option<&'a str>,
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for PageView<'a> {
    type Owned = super::super::Page;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.field1 = Some(::buffa::types::borrow_str(&mut cur)?);
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.field2 = Some(::buffa::types::borrow_str(&mut cur)?);
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.field3 = Some(::buffa::types::decode_int32(&mut cur)?);
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.text1 = Some(::buffa::types::borrow_str(&mut cur)?);
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.published.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.published = ::buffa::MessageFieldView::set(
                            <::buffa_types::google::protobuf::__buffa::view::TimestampView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.appendix = Some(::buffa::types::borrow_str(&mut cur)?);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Page, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Page, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Page {
            field1: self.field1.map(|s| s.to_string()),
            field2: self.field2.map(|s| s.to_string()),
            field3: self.field3,
            text1: self.text1.map(|s| s.to_string()),
            published: match self.published.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        ::buffa_types::google::protobuf::Timestamp,
                        ::buffa::Inline<::buffa_types::google::protobuf::Timestamp>,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            appendix: self.appendix.map(|s| s.to_string()),
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for PageView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if let Some(ref v) = self.field1 {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if let Some(ref v) = self.field2 {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if let Some(v) = self.field3 {
            size += 1u64 + ::buffa::types::int32_encoded_len(v) as u64;
        }
        if let Some(ref v) = self.text1 {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if self.published.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.published.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if let Some(ref v) = self.appendix {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if let Some(ref v) = self.field1 {
            ::buffa::types::put_string_field(1u32, v, buf);
        }
        if let Some(ref v) = self.field2 {
            ::buffa::types::put_string_field(2u32, v, buf);
        }
        if let Some(v) = self.field3 {
            ::buffa::types::put_int32_field(3u32, v, buf);
        }
        if let Some(ref v) = self.text1 {
            ::buffa::types::put_string_field(4u32, v, buf);
        }
        if self.published.is_set() {
            ::buffa::types::put_len_delimited_header(
                5u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.published.write_to(__cache, buf);
        }
        if let Some(ref v) = self.appendix {
            ::buffa::types::put_string_field(6u32, v, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for PageView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if let ::core::option::Option::Some(__v) = self.field1 {
            __map.serialize_entry("field1", __v)?;
        }
        if let ::core::option::Option::Some(__v) = self.field2 {
            __map.serialize_entry("field2", __v)?;
        }
        if let ::core::option::Option::Some(__v) = self.field3 {
            __map.serialize_entry("field3", &::buffa::json_helpers::ProtoJson(&__v))?;
        }
        if let ::core::option::Option::Some(__v) = self.text1 {
            __map.serialize_entry("text1", __v)?;
        }
        {
            if let ::core::option::Option::Some(__v) = self.published.as_option() {
                __map.serialize_entry("published", __v)?;
            }
        }
        if let ::core::option::Option::Some(__v) = self.appendix {
            __map.serialize_entry("appendix", __v)?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for PageView<'a> {
    const PACKAGE: &'static str = "markdown.testdata";
    const NAME: &'static str = "Page";
    const FULL_NAME: &'static str = "markdown.testdata.Page";
    const TYPE_URL: &'static str = "type.googleapis.com/markdown.testdata.Page";
}
::buffa::impl_default_view_instance!(PageView);
::buffa::impl_view_reborrow!(PageView);
/** Self-contained, `'static` owned view of a `Page` message.

 Wraps [`::buffa::OwnedView`]`<`[`PageView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`PageView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct PageOwnedView(::buffa::OwnedView<PageView<'static>>);
impl PageOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(PageOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PageOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Page,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(PageOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`PageView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &PageView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Page {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `field1`
    #[must_use]
    pub fn field1(&self) -> ::core::option::Option<&'_ str> {
        self.0.reborrow().field1
    }
    /// Field 2: `field2`
    #[must_use]
    pub fn field2(&self) -> ::core::option::Option<&'_ str> {
        self.0.reborrow().field2
    }
    /// Field 3: `field3`
    #[must_use]
    pub fn field3(&self) -> ::core::option::Option<i32> {
        self.0.reborrow().field3
    }
    /// Field 4: `text1`
    #[must_use]
    pub fn text1(&self) -> ::core::option::Option<&'_ str> {
        self.0.reborrow().text1
    }
    /// Field 5: `published`
    #[must_use]
    pub fn published(
        &self,
    ) -> &::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'_>,
    > {
        &self.0.reborrow().published
    }
    /// Field 6: `appendix`
    #[must_use]
    pub fn appendix(&self) -> ::core::option::Option<&'_ str> {
        self.0.reborrow().appendix
    }
}
impl ::core::convert::From<::buffa::OwnedView<PageView<'static>>> for PageOwnedView {
    fn from(inner: ::buffa::OwnedView<PageView<'static>>) -> Self {
        PageOwnedView(inner)
    }
}
impl ::core::convert::From<PageOwnedView> for ::buffa::OwnedView<PageView<'static>> {
    fn from(wrapper: PageOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<PageView<'static>>> for PageOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<PageView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Page {
    type View<'a> = PageView<'a>;
    type ViewHandle = PageOwnedView;
}
impl ::serde::Serialize for PageOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
