//! Generated protobuf types from `proto/markdown` (public options plus
//! testdata fixtures).
//!
//! Regenerated by `bazel run //proto/markdown:generate` (buffa + packaging
//! plugins). Call sites use `serde_markdown_generated::markdown::{...}`.

#[rustfmt::skip]
#[path = "markdown/mod.rs"]
mod generated;

pub use generated::markdown;
