load("@bazel_utils_rust//:rust.bzl", "cargo_audit_test")
load("@rules_rust//rust:defs.bzl", "rust_clippy_test")
load("//bazel:compat.bzl", "NOT_WINDOWS")

rust_clippy_test(
    name = "lint",
    size = "small",
    targets = [
        "//rust/generated:generated",
        "//rust/generated:generated_test",
        "//rust/serde_markdown:serde_markdown",
        "//rust/serde_markdown:serde_markdown_test",
        "//rust/serde_markdown_derive:serde_markdown_derive",
    ],
)

cargo_audit_test(
    name = "vuln",
    size = "small",
    target_compatible_with = NOT_WINDOWS,
)
