load("@bazel_utils_rust//:rust.bzl", "cargo_audit_test")
load("@rules_rust//rust:defs.bzl", "rust_clippy_test")
load("//bazel:compat.bzl", "NOT_WINDOWS")

rust_clippy_test(
    name = "lint",
    size = "small",
    targets = [
        "//rust/examples/page:lib",
        "//rust/examples/page:lib_test",
        "//rust/examples/page:page",
        "//rust/examples/protobuf:lib",
        "//rust/examples/protobuf:lib_test",
        "//rust/examples/protobuf:protobuf",
        "//rust/examples/tokio:lib",
        "//rust/examples/tokio:lib_test",
        "//rust/examples/tokio:tokio",
        "//rust/proto",
        "//rust/proto:test",
        "//rust/markdown:serde_markdown",
        "//rust/markdown:serde_markdown_test",
        "//rust/markdown:serde_markdown_no_json",
        "//rust/markdown:serde_markdown_no_json_test",
        "//rust/markdown:serde_markdown_no_toml",
        "//rust/markdown:serde_markdown_no_toml_test",
        "//rust/markdown:serde_markdown_no_yaml",
        "//rust/markdown:serde_markdown_no_yaml_test",
        "//rust/markdown_derive:serde_markdown_derive",
    ],
)

cargo_audit_test(
    name = "vuln",
    size = "small",
    target_compatible_with = NOT_WINDOWS,
)
